//
//  FinixHelper.swift
//  FinixTest
//
//  Created by Tushar Jadhav on 20/04/22.
//

import Foundation
import FinixPOS

public protocol FinixHelperDelegate : AnyObject {
    
    /// SDK Initialization
    func sdkInitialzed(error: Error?)
    
    /// SDK Deinitialization
    func sdkDeinitialzed(error: Error?)
    
    /// On reader connection.
    /// - Parameter description: descriptor for the device e.g. "BBPOS"
    /// - Parameter model: device model e.g. "CHB20"
    /// - Parameter serialNumber: unique identifer for the device e.g. "CHBXXXXXXXXXXXX"
    func deviceDidConnect(_ description: String, model: String, serialNumber: String)
    
    /// On device disconnection complete.
    func deviceDidDisconnect()
    
    /// On reader initialization.
    /// - Parameter currentProgress: percentage progress
    /// - Parameter description: description for the device e.g. "BBPOS"
    /// - Parameter model: device model e.g. "CHB20"
    /// - Parameter serialNumber: unique identifer for the device e.g. "CHBXXXXXXXXXXXX"    ///
    func deviceInitialization(inProgress currentProgress: Double, description: String, model: String, serialNumber: String)
    
    /// On reader error.
    /// - Parameter error: error generated by the device
    func deviceDidError(_ error: Error)
    
    /// on `DeviceStatus` change
    /// - Parameter status: the `DeviceStatus`
    /// - Parameter description: description of the status change
    func statusDidChange(_ status: FinixPOS.DeviceStatus, description: String)
    
    /// Sent when the battery of the reader is low.
    func onBatteryLow()
    
    /// Recently pre-read data has timed out
    func prereadTimedOut()
    
    /// When text is to be shown to the user. e.g. "Insert, Tap or Swipe Card"
    /// - Parameter text: text to show the user
    func onDisplayText(_ text: String)
    
    /// Inform card removal
    func onRemoveCard()
    
    /// Sale Performed with Error
    func saleResponseFailed(error: Error)
    
    /// Sale Performed with Success, but check for any error
    func saleResponseSuccess(response: String)
}

let FINIXHELPER = FinixHelper.sharedFinixHelper

private let _sharedFinixHelper = FinixHelper()

class FinixHelper {
    
    class var sharedFinixHelper: FinixHelper {
        
        return _sharedFinixHelper
    }
    
    weak var finixHelperDelegate: FinixHelperDelegate?
    
    var deviceId: String = ""
    
    func initializeFinixSDK(environment: FinixPOS.Finix.Environment,
                            userName: String,
                            password: String,
                            application: String,
                            version: String,
                            merchantId: String,
                            deviceID: String,
                            serialNumber: String?) {
        
        let config = FinixConfig(environment: environment,
                                 credentials: Finix.APICredentials(username: userName, password: password),
                                 application: application,
                                 version: version,
                                 merchantId: merchantId,
                                 marketCode: .qsr,
                                 deviceType: .BBPOS,
                                 deviceId: deviceID,
                                 serialNumber: serialNumber)
        
        deviceId = deviceID
        
        let client = FinixClient.shared
        client.delegate = self
        client.interactionDelegate = self
        
        client.syncSDK(config: config) { success, error in
            
            if let delegate = self.finixHelperDelegate {
                
                delegate.sdkInitialzed(error: error)
            }
            
            guard success == true else {
                
                // print("==========FinixSDK: failed to initalize with error \(error!)==========")
                
                return
            }
            
            // print("==========FinixSDK: initialized successfully.==========")
        }
    }
    
    func deinitializeFinixSDK() {
        
        let client = FinixClient.shared
        
        client.unsyncSDK { error in
            
            if let delegate = self.finixHelperDelegate {
                
                delegate.sdkDeinitialzed(error: error)
            }
            
            // print("==========FinixSDK: deinitialized==========")
            
            if error != nil {
                
                // print("==========Error Deinitializing SDK: \(error.localizedDescription)==========")
            }
        }
    }
    
    func performSale(billAmount: Decimal, testTags: ResourceTags) {
        
        // before performing sale, present the user an ActionSheet to adjust the amount.
        // upon submission, show the device's input status.
        let saleAmount = Currency(decimal: billAmount, code: .USD)
        
        let transfer = TransferRequest(deviceId: self.deviceId, amount: saleAmount, tags: testTags)
        
        // print("==========Transfer Request: \(transfer)==========")
        
        FinixClient.shared.cardSale(transfer) { response, error in
            
            guard let response = response else {
                
                // print("==========Failed with error : \(error!)==========")
                
                if let delegate = self.finixHelperDelegate {
                    
                    delegate.saleResponseFailed(error: error!)
                }
                
                return
            }
            
            let responseText = String(describing: response)
            
            if response.success {
                
                let receipt = FinixClient.shared.receipt(for: response)
                let receiptText = String(describing: receipt)
                
                // print("==========Success response: \(responseText), Transfer Id: \(response.id)==========")
                // print("==========Sale Receipt: \(receiptText)==========")
                
                if let delegate = self.finixHelperDelegate {
                    
                    delegate.saleResponseSuccess(response: receiptText)
                }
                
            } else {
                
                // print("==========Not Successful response: \(responseText)==========")
                
                if let delegate = self.finixHelperDelegate {
                    
                    delegate.saleResponseSuccess(response: responseText)
                }
            }
        }
    }
    
    func cancelSale() -> Bool {
        
        return FinixClient.shared.stopCurrentOperation()
    }
    
    func isReaderConnected() -> Bool {
        
        return FinixClient.shared.isReaderConnected()
    }
    
    func isSDKInitialized() -> Bool {
        
        return FinixClient.shared.isInitialized()
    }
}

extension FinixHelper: FinixDelegate {
    
    func deviceDidConnect(_ description: String, model: String, serialNumber: String) {
        
        // print("==========Device Did Connect:\nDescription:\(description)\nmodel:\(model)\nserial:\(serialNumber)==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.deviceDidConnect(description, model: model, serialNumber: serialNumber)
        }
    }
    
    func deviceDidDisconnect() {
        
        // print("==========Device Did Disconnect==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.deviceDidDisconnect()
        }
    }
    
    func deviceInitialization(inProgress currentProgress: Double, description: String, model: String, serialNumber: String) {
        
        // print("==========Device Initialization:\nProgress:\(currentProgress)\nDescription:\(description)\nmodel:\(model)\nserial:\(serialNumber)==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.deviceInitialization(inProgress: currentProgress, description: description, model: model, serialNumber: serialNumber)
        }
    }
    
    func deviceDidError(_ error: Error) {
        
        // print("==========Device Did Error: \(error.localizedDescription)==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.deviceDidError(error)
        }
    }
    
    func statusDidChange(_ status: DeviceStatus, description: String) {
        
        // print("==========Device Status change:\(status), description:\(description)==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.statusDidChange(status, description: description)
        }
    }
    
    func onBatteryLow() {
        
        // print("==========Device Battery Low==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.onBatteryLow()
        }
    }
    
    func prereadTimedOut() {
        
        // print("==========Device Preread Time Out==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.prereadTimedOut()
        }
    }
}

extension FinixHelper: FinixClientDeviceInteractionDelegate {
    
    func onDisplayText(_ text: String) {
        
        // print("==========On display text: \(text)==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.onDisplayText(text)
        }
    }
    
    func onRemoveCard() {
        
        // print("==========Card removed==========")
        
        if let delegate = self.finixHelperDelegate {
            
            delegate.onRemoveCard()
        }
    }
}
